language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aks2mail/multi-docker -f ./client/Dockerfile.dev

script:
    #- docker run -e CI=true aks2mail/multi-docker npm run test 
    - docker run aks2mail/multi-docker npm test -- --coverage

after_success:
    - docker build -t aks2mail/multi-client ./client
    - docker build -t aks2mail/multi-nginx ./nginx
    - docker build -t aks2mail/multi-server ./server
    - docker build -t aks2mail/multi-worker ./worker
#login in to the docker cli 
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to docker hub
- docker push aks2mail/multi-client
- docker push aks2mail/multi-nginx
- docker push aks2mail/multi-server
- docker push aks2mail/multi-worker